url = 'http://localhost:8000'
output = 'dist/'
workers_count = 10

[js]
enabled = true
wait_for = 2000
flags = ["--no-sandbox"]

[pages]
entrypoints = ['/']
extract_only = ['/_/entries']
exclude = []
