name: ci
on:
  push:
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      # PHP Setup
      - name: Cache composer packages
        id: cache-composer
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-packages
        with:
          path: ~/.composer-store
          key: build-${{ env.cache-name }}-${{ hashFiles('website/composer.lock') }}

      - name: Install PHP dependencies
        run: nix develop --ignore-environment --keep COMPOSER_HOME --command composer install
        env:
          COMPOSER_HOME: ~/.composer-store

      - name: Build logosnatch
        run: nix develop --command go build
        working-directory: ./tools/logosnatch
        env:
          GOMODCACHE: /home/runner/.go-store

      - name: Run tests
        run: nix develop --ignore-environment --keep COMPOSER_HOME --command composer test
        env:
          COMPOSER_HOME: ~/.composer-store
