name: deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Install node dependencies
        run: nix develop --ignore-environment --command pnpm install
      - name: Build assets
        run: nix develop --ignore-environment --command pnpm build
      - name: Install PHP dependencies
        run: nix develop --ignore-environment --keep HOME --command composer install --no-dev -o
      - name: Copy .env
        run: cp .env.example .env
      - name: Generate secret key
        run: php artisan key:generate
      - name: Build website
        run: nix develop --ignore-environment --command php artisan export
      - name: Deploy website
        run: nix develop --ignore-environment --command wrangler deploy ./dist --project-name biosecurity-world --branch master
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}