name: report-hydration-errors
on:
  pull_request:
jobs:
  report-hydration-errors:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - name: Cache composer packages
        id: cache-composer
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-packages
        with:
          path: ~/.composer-store
          key: build-${{ env.cache-name }}-${{ hashFiles('website/composer.lock') }}
      - name: Install PHP dependencies
        run: nix develop --ignore-environment --keep COMPOSER_HOME --command composer install --no-dev -o
        env:
          COMPOSER_HOME: ~/.composer-store
      - name: Copy .env
        run: cp .env.example .env
      - name: Report hydration errors
        run: nix develop --ignore-environment --command php artisan app:report-hydration-errors
      - name: Comment changes
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: /home/runner/report.md
          pr_number: ${{ github.event.number }}
          comment_tag: "Hydration Errors"
